version: '2.4'
services:

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - app
      - redis
      - phpredisadmin
      - certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  app:
    build: .
    ports:
     - "8080:8080"
    depends_on:
      - redis

  countall:
    build: .
    command: "node countAll.js"
    depends_on:
      - redis
      - app
    env_file:
      - 'variables.env'

  countlastmonth:
    build: .
    command: "node countLastMonth.js"
    depends_on:
      - redis
      - app
    env_file:
      - 'variables.env'

  redis-overcommit:
    build: https://github.com/bkuhl/redis-overcommit-on-host.git
    restart: 'no'
    privileged: true
    volumes:
      - /proc/sys/vm:/mnt/vm

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
    depends_on:
      - redis-overcommit

  trends:
    build: trends
    depends_on:
      - redis
    env_file:
      - 'variables.env'
    volumes:
      - trends-data:/opt/trends/es_dumps
    cpus: 1.5
    mem_limit: 6G
    oom_kill_disable: true

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    depends_on:
      - redis
    env_file:
      - secret.env

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  redis-data:
  trends-data:
