version: '3.3'
services:

  web:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - app
      - redis
      - phpredisadmin
      - certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  app:
    build: .
    ports:
     - "8080:8080"
    depends_on:
      - redis

  countall:
    build: .
    command: "node countAll.js"
    depends_on:
      - redis
      - app

  countlastmonth:
    build: .
    command: "node countLastMonth.js"
    depends_on:
      - redis
      - app

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - /usr/local/etc/redis/redis.conf

  trends:
    build: trends
    depends_on:
      - redis

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=oritrends
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    depends_on:
      - redis
    # ports:
    #   - '8888:80'

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
  redis-data:
